### ISSUE TITLE
로그인 누를 시 정보 받아오기2

### ISSUE THREAD

**Issue by dizzymon2** [ProjectInTheClass/Sue4U#5]
thumbnail 이미지 로드
가입 form 완성(e-mail, phone number)

**Comment by likegreen591** [comment]
이미지 로드 라이브러리 써서 완료했습니다. 
MapleBacon Image Loader : https://github.com/zalando/MapleBacon
UIImageView.setImage(url: url)로 url에 해당하는 이미지를 뷰의 이미지로 설정
